spring.application.name=INFERA

server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:8080/INFERA_DB
spring.datasource.username=postgres
spring.datasource.password=${INFERA_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML

#OAuth2
    #Google
spring.security.oauth2.client.registration.google.client-id=${INFERA_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${INFERA_GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,profile,email
    #GitHub
spring.security.oauth2.client.registration.github.client-id=${INFERA_GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${INFERA_GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

    #Microsoft
#spring.security.oauth2.client.registration.microsoft.client-id=${INFERA_MICROSOFT_CLIENT_ID}
#spring.security.oauth2.client.registration.microsoft.client-secret=${INFERA_MICROSOFT_CLIENT_SECRET}
#spring.security.oauth2.client.registration.microsoft.scope=openid,profile,email
#spring.security.oauth2.client.provider.microsoft.issuer-uri=https://login.microsoftonline.com/common/v2.0
   #File Upload
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=3MB
app.upload-dir=uploads/avatars
#BREVO
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=b60fc4001@smtp-brevo.com
spring.mail.password=xsmtpsib-545983f02aeb11e41306cb2d845f8d0e057b885f60bd379e8234cab5a7e2f552-edpmuIpqXjmLZbv6
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=belmiredub4@gmail.com
app.mail.from-name=INFERA

