spring.application.name=INFERA

server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:8080/INFERA_DB
spring.datasource.username=postgres
spring.datasource.password=2286
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML

#OAuth2
    #Google
spring.security.oauth2.client.registration.google.client-id=739857784524-u974r31hderr3b364d10aldlco1ceuap.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
    #GitHub
spring.security.oauth2.client.registration.github.client-id=Ov23likJozDCoVKdcrXp
spring.security.oauth2.client.registration.github.client-secret=ca2ba8678472299f5d952c77104f88952a6271bc
spring.security.oauth2.client.registration.github.scope=read:user,user:email

