spring.application.name=INFERA

server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:8080/INFERA_DB
spring.datasource.username=postgres
spring.datasource.password=${INFERA_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML

#OAuth2
    #Google
spring.security.oauth2.client.registration.google.client-id=${INFERA_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${INFERA_GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,profile,email
    #GitHub
spring.security.oauth2.client.registration.github.client-id=${INFERA_GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${INFERA_GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

